name: aesbube-dev

services:
  app:
    container_name: aesbube-dev
    image: aesbube/personal-website:latest
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production